apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namesuffix.service }}
  namespace: default
spec:
  selector:
    app: nginx-customized
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port}}
    nodePort: {{ .Values.service.nodePort }}